//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basvurular
    {
        public int id { get; set; }
        public string tarih { get; set; }
        public string basAd { get; set; }
        public string basSoyad { get; set; }
        public string telNo { get; set; }
        public string sehir { get; set; }
        public string adres { get; set; }
        public string yabanciDil { get; set; }
        public string egitimDurum { get; set; }
        public string mezunOkul { get; set; }
        public string cinsiyet { get; set; }
        public string cv { get; set; }
    }
}
