//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKYS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IKYSEntities : DbContext
    {
        public IKYSEntities()
            : base("name=IKYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACalisan> ACalisans { get; set; }
        public virtual DbSet<Basvurular> Basvurulars { get; set; }
        public virtual DbSet<Calisanlar> Calisanlars { get; set; }
        public virtual DbSet<Dilekceler> Dilekcelers { get; set; }
        public virtual DbSet<Izinliler> Izinlilers { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Yonetici> Yoneticis { get; set; }
    }
}
