//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izinliler
    {
        public int id { get; set; }
        public string departman { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string telNo { get; set; }
        public string sgNo { get; set; }
        public string adres { get; set; }
        public string cinsiyet { get; set; }
        public string mail { get; set; }
        public string izinBas { get; set; }
        public string izinBit { get; set; }
    }
}
