//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int id { get; set; }
        public string sifre { get; set; }
        public string resim { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string telNo { get; set; }
        public Nullable<int> maas { get; set; }
        public string adres { get; set; }
        public string sgNo { get; set; }
    }
}
