//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKYS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int logid { get; set; }
        public int kullid { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string eylem { get; set; }
        public Nullable<System.DateTime> saat { get; set; }
    }
}
